import type { CloudEntry, CloudProvider, PlaybackLink, ProviderHealth } from '../provider';
import { ProviderRateGate, abortableSleep } from '../rate-limit';
import { decrypt115, encrypt115 } from './cloud115-crypto';

const DEFAULT_UA = 'Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.0 Mobile/15E148 Safari/604.1';
interface Raw115Entry { n?:string; fid?:string|number; cid?:string|number; s?:string|number; sha?:string|null; pc?:string; pick_code?:string; fc?:number; }
interface FilesResponse { state?:boolean; errno?:number; error?:string; count?:number; data?:Raw115Entry[]; }
export class Cloud115Error extends Error { constructor(message:string,readonly status?:number,readonly code?:number){super(message);this.name='Cloud115Error';} }
export class Cloud115Provider implements CloudProvider {
 readonly kind='115' as const; readonly rootId='0'; readonly capabilities={read:true,directPlay:true,write:false} as const;
 private readonly cookie:string; private readonly defaultUserAgent:string; private readonly gate:ProviderRateGate;
 constructor(opts?:{cookie?:string;userAgent?:string;maxConcurrent?:number;maxPerSecond?:number}){this.cookie=opts?.cookie??process.env.ONEHUBX_115_COOKIE??'';this.defaultUserAgent=opts?.userAgent??process.env.ONEHUBX_115_USER_AGENT??DEFAULT_UA;this.gate=new ProviderRateGate(opts?.maxConcurrent??intEnv('ONEHUBX_115_MAX_CONCURRENT',1,1,2),opts?.maxPerSecond??numberEnv('ONEHUBX_115_MAX_RPS',1,0.2,5));}
 get configured(){return this.cookie.trim().length>0;}
 async healthCheck(signal?:AbortSignal):Promise<ProviderHealth>{if(!this.configured)return{ok:false,message:'未配置 ONEHUBX_115_COOKIE'};try{await this.listDir(this.rootId,signal,1);return{ok:true,message:'115 连接正常'};}catch(error){return{ok:false,message:toMessage(error)};}}
 async listDir(id:string,signal?:AbortSignal,pageLimit=1000):Promise<CloudEntry[]>{this.assertConfigured();const all:CloudEntry[]=[];const limit=Math.max(1,Math.min(pageLimit,1000));for(let offset=0;;offset+=limit){const params=new URLSearchParams({cid:id||'0',limit:String(limit),offset:String(offset)});const page=await this.requestJson<FilesResponse>(`https://webapi.115.com/files?${params}`,{method:'GET',signal});ensureBusinessOk(page);const items=page.data??[];all.push(...items.map(toCloudEntry));if(items.length<limit||(typeof page.count==='number'&&all.length>=page.count))break;}return all;}
 async resolvePath(path:string,signal?:AbortSignal):Promise<CloudEntry|null>{const parts=path.split('/').map(x=>x.trim()).filter(Boolean);if(parts.length===0)return{id:this.rootId,name:'/',isDir:true};let parent=this.rootId,current:CloudEntry|null=null;for(const segment of parts){const entries=await this.listDir(parent,signal);current=entries.find(e=>e.name===segment)??null;if(!current)return null;parent=current.id;}return current;}
 async getPlaybackLink(entry:Pick<CloudEntry,'id'|'name'|'token'>,opts?:{userAgent?:string;signal?:AbortSignal}):Promise<PlaybackLink>{this.assertConfigured();const ua=opts?.userAgent?.trim()||this.defaultUserAgent;const pickCode=entry.token||(await this.getPickCode(entry.id,ua,opts?.signal));const payload=`data=${encodeURIComponent(encrypt115(`{"pick_code":"${pickCode}"}`))}`;const response=await this.requestJson<{data?:string;state?:boolean;errno?:number;error?:string}>('https://proapi.115.com/android/2.0/ufile/download',{method:'POST',body:payload,signal:opts?.signal,userAgent:ua,commonHeaders:false,headers:{'Content-Type':'application/x-www-form-urlencoded'}});ensureBusinessOk(response);if(!response.data)throw new Cloud115Error('115 未返回播放地址数据');const decrypted=JSON.parse(decrypt115(response.data)) as {url?:string};if(!decrypted.url)throw new Cloud115Error('115 未返回有效播放地址');return{url:decrypted.url};}
 private async getPickCode(fileId:string,userAgent:string,signal?:AbortSignal){const response=await this.requestJson<{state?:boolean;errno?:number;error?:string;data?:Array<{pick_code?:string}>}>(`https://webapi.115.com/files/file?file_id=${encodeURIComponent(fileId)}`,{method:'GET',signal,userAgent,commonHeaders:false});ensureBusinessOk(response);const pick=response.data?.[0]?.pick_code;if(!pick)throw new Cloud115Error(`115 文件 ${fileId} 没有 pick_code`);return pick;}
 private async requestJson<T>(url:string,opts:{method:'GET'|'POST';body?:string;headers?:Record<string,string>;userAgent?:string;commonHeaders?:boolean;signal?:AbortSignal}):Promise<T>{const retries=intEnv('ONEHUBX_115_RETRIES',2,0,3);let lastError:unknown;for(let attempt=0;attempt<=retries;attempt++){try{return await this.gate.schedule(async()=>{const ua=opts.userAgent||this.defaultUserAgent;const headers:Record<string,string>={'User-Agent':ua,Cookie:this.cookie,...(opts.commonHeaders===false?{}:{Accept:'application/json, text/plain, */*',Referer:'https://115.com/',Origin:'https://115.com'}),...opts.headers};const timeoutSignal=AbortSignal.timeout(intEnv('ONEHUBX_115_TIMEOUT_MS',12000,3000,30000));const signal=opts.signal?AbortSignal.any([opts.signal,timeoutSignal]):timeoutSignal;const response=await fetch(url,{method:opts.method,headers,body:opts.body,signal,redirect:'follow'});const text=await response.text();let data:unknown;try{data=text?parseJsonPreservingLargeIntegers(text):{};}catch{throw new Cloud115Error(`115 返回非 JSON 数据（HTTP ${response.status}）`,response.status);}if(!response.ok)throw new Cloud115Error(`115 接口 HTTP ${response.status}: ${summarize(data)}`,response.status);return data as T;},opts.signal);}catch(error){lastError=error;if(attempt>=retries||!retryable(error))break;await abortableSleep(Math.min(4000,500*2**attempt),opts.signal);}}throw lastError;}
 private assertConfigured(){if(!this.configured)throw new Cloud115Error('未配置 ONEHUBX_115_COOKIE');}
}
function toCloudEntry(raw:Raw115Entry):CloudEntry{const isDir=!raw.sha&&(raw.fid===undefined||raw.fid===null||raw.fid===0);const id=String(isDir?raw.cid??'0':raw.fid??raw.cid??'');return{id,name:String(raw.n??''),isDir,size:raw.s==null?undefined:Number(raw.s),hash:raw.sha||undefined,token:raw.pc||raw.pick_code||undefined};}
function ensureBusinessOk(value:unknown){if(!value||typeof value!=='object')throw new Cloud115Error('115 返回空响应');const obj=value as {state?:boolean;errno?:number;error?:string};if(obj.state===false||(obj.errno&&obj.errno!==0))throw new Cloud115Error(obj.error?.trim()||`115 业务错误 ${obj.errno??''}`.trim(),undefined,obj.errno);}
function retryable(error:unknown){if(error instanceof Cloud115Error){if(error.status===429)return true;if(error.status&&error.status>=500)return true;return false;}return error instanceof TypeError||(error instanceof DOMException&&error.name==='TimeoutError');}
function parseJsonPreservingLargeIntegers(text:string){return JSON.parse(text.replace(/([:\[,]\s*)(-?\d{16,})(?=\s*[,}\]])/g,'$1"$2"'));}
function summarize(value:unknown){try{return JSON.stringify(value).slice(0,180);}catch{return String(value).slice(0,180);}}
function toMessage(error:unknown){return error instanceof Error?error.message:String(error);}
function intEnv(name:string,fallback:number,min:number,max:number){const n=Number.parseInt(process.env[name]??'',10);return Number.isFinite(n)?Math.max(min,Math.min(max,n)):fallback;}
function numberEnv(name:string,fallback:number,min:number,max:number){const n=Number(process.env[name]);return Number.isFinite(n)?Math.max(min,Math.min(max,n)):fallback;}
